apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: spark-postgres
type: Opaque
stringData:
  POSTGRES_USER: "sparkuser"
  POSTGRES_PASSWORD: "sparkpass"
  POSTGRES_DB: "sparkdb"