apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  labels:
    app: spark
    role: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      role: worker
  template:
    metadata:
      labels:
        app: spark
        role: worker
    spec:
      containers:
        - name: spark-worker
          image: spark-app:v1
          command: ["/opt/spark/bin/spark-class"]
          args:
            - org.apache.spark.deploy.worker.Worker
            - spark://sprk-mstr:7077
            - --cores
            - "2"
            - --memory
            - "1g"