apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  labels:
    app: spark
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      role: master
  template:
    metadata:
      labels:
        app: spark
        role: master
    spec:
      containers:
        - name: spark-master
          image: spark-app:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7077
            - containerPort: 8080
          command: ["/opt/spark/bin/spark-class"]
          args:
            - org.apache.spark.deploy.master.Master
            - --host
            - "0.0.0.0"
            - --port
            - "7077"
            - --webui-port
            - "8080"
          volumeMounts:
            - name: spark-workdir
              mountPath: /opt/spark/work-dir
      volumes:
        - name: spark-workdir
          emptyDir: {}