apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  labels:
    app: spark
    role: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      role: worker
  template:
    metadata:
      labels:
        app: spark
        role: worker
    spec:
      initContainers:
        - name: init-work-dir-permissions
          image: busybox:1.36
          command: ['sh', '-c', 'chown -R 999:999 /opt/spark/work-dir']
          volumeMounts:
            - name: spark-worker-dir
              mountPath: /opt/spark/work-dir
      containers:
        - name: spark-worker
          image: spark-app:v1
          imagePullPolicy: IfNotPresent
          command: ["/opt/spark/bin/spark-class"]
          args:
            - org.apache.spark.deploy.worker.Worker
            - spark://sprk-mstr:7077
            - --host
            - "0.0.0.0"
            - --port
            - "8888"
            - --cores
            - "2"
            - --memory
            - "1g"
            - --work-dir
            - "/opt/spark/work-dir"
          ports:
            - containerPort: 8888
          volumeMounts:
            - name: spark-worker-dir
              mountPath: /opt/spark/work-dir
      volumes:
        - name: spark-worker-dir
          emptyDir: {}
