apiVersion: v1
kind: Service
metadata:
  name: sprk-mstr
spec:
  selector:
    app: spark
    role: master
  ports:
    - name: rpc
      port: 7077
      targetPort: 7077
    - name: webui
      port: 8080
      targetPort: 8080